import { LegalPage, legalMetadata, OPERATOR } from '@/components/legal/LegalPage';

export const metadata = legalMetadata(
  'Accessibility Statement',
  'IgniteAI Studio’s accessibility commitments, known limitations, and how to report a barrier.'
);

export default function AccessibilityPage() {
  return (
    <LegalPage
      title="Accessibility Statement"
      intro="IgniteAI Studio aims to be usable by everyone, including people using a screen reader, keyboard-only navigation, magnification or reduced motion."
    >
      <h2>Target standard</h2>
      <p>
        We aim to meet <strong>WCAG 2.1 Level AA</strong>. We treat that as an ongoing commitment
        rather than a finished certification, and gaps are fixed as they are found.
      </p>

      <h2>What is in place today</h2>
      <ul>
        <li>
          <strong>Keyboard access.</strong> Every interactive control is reachable and operable by
          keyboard. Dropdowns are custom listboxes supporting arrow keys, Home and End, Enter and
          Space to choose, Escape to dismiss, and first-letter typeahead.
        </li>
        <li>
          <strong>Visible focus.</strong> A high-contrast focus ring is shown on every focusable
          element, and it is never suppressed.
        </li>
        <li>
          <strong>Screen readers.</strong> Semantic landmarks and headings throughout; ARIA
          combobox and listbox semantics on dropdowns; labelled form controls; status and alert
          roles on loading, success and error blocks so changes are announced.
        </li>
        <li>
          <strong>Contrast.</strong> The light and dark themes are both tuned for AA contrast; the
          brand red is darkened in light mode specifically to hold contrast on white.
        </li>
        <li>
          <strong>Reduced motion.</strong> Animations and transitions are disabled automatically for
          anyone whose system requests reduced motion.
        </li>
        <li>
          <strong>Theme choice.</strong> A light and a dark theme are both available and remembered
          between visits.
        </li>
        <li>
          <strong>Responsive layout.</strong> The interface reflows down to small screens and
          supports browser zoom without loss of function.
        </li>
        <li>
          <strong>Meaningful icons.</strong> Decorative icons are hidden from assistive technology;
          icon-only buttons carry accessible labels.
        </li>
      </ul>

      <h2>Known limitations</h2>
      <ul>
        <li>
          Content generated by AI models is not checked for reading level or plain-language quality;
          that depends on the model and the tone you select.
        </li>
        <li>
          Text extracted from a scanned PDF is only as good as that PDF &mdash; an image-only
          document with no text layer cannot be read by the service or by your screen reader.
        </li>
        <li>
          Long tabular observability output can require horizontal scrolling on narrow screens.
        </li>
      </ul>

      <h2>Reporting a barrier</h2>
      <p>
        If something here is difficult or impossible for you to use, tell us &mdash; that report is
        the fastest route to a fix. Email{' '}
        <a href={`mailto:${OPERATOR.email}`}>{OPERATOR.email}</a> describing the page, what you were
        trying to do, and the assistive technology and browser you were using. We aim to acknowledge
        within five working days and will tell you what we can do and when.
      </p>

      <h2>Alternative access</h2>
      <p>
        If a part of the interface blocks you, contact the operator at the address above and we will
        work with you to achieve the same outcome another way.
      </p>
    </LegalPage>
  );
}
